server:
  port: 9011

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: ANIME-SERVICE
          uri: lb://ANIME-SERVICE
          predicates:
            - Path=/anime/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

